### PR TITLE
Fix ruby 2.7 warnings

### LINKED ISSUE #5: Fix argument fowarding
Due to the changes introduced in Ruby 2.7, it's necessary to fix the syntax for argument forwarding used on Fservice::Base.

Info:
https://bugs.ruby-lang.org/issues/16157
https://eregon.me/blog/2019/11/10/the-delegation-challenge-of-ruby27.html

### PR DESCRIPTION
**Pull request by matheusbsilva**
Fix argument forwarding due to [Separation of positional and keyword arguments in Ruby 3.0](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/).

Closes #5

### CODE REVIEW

File: lib/f_service/base.rb [hunk 1]
```diff
@@ -25,13 +20,35 @@ class Base
...
+      #
+      #   [{ n:1 }, { n: 2 }].map(&DoubleNumber).map(&:value)
+      #   # => [2, 4]
+      #
+      # @return [Proc]
+      def to_proc
+        proc { |args| call(**args) }
+      end
+
+      ruby2_keywords :call if respond_to?(:ruby2_keywords, true)
```
Comment (MatheusRich) [inline lib/f_service/base.rb:50]: Can you move this right after the `def call` itself?

**Review by MatheusRich — CHANGES_REQUESTED** [review]

File: lib/f_service/base.rb (hunk 1 above)
Comment (matheusbsilva) [reply lib/f_service/base.rb]: Done.

**Comment by MatheusRich** [comment]
Thanks @matheusbsilva!
